### ISSUE TITLE
Doesn't work with recent confluence cloud

### ISSUE THREAD

**Issue by ekropotin** [skleinei/alfred-confluence#7]
I followed the instruction, set base url, username and password but getting 403 error:

```
Starting debug for 'Confluence Quick Search v1.0.3'

[2020-01-25 22:21:29][ERROR: input.scriptfilter] Code 1: 22:21:28 workflow.py:1859 DEBUG    Loading cached data from : /Users/ekropotin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.k15t.labs.alfredapp.confluence.quicksearch/__workflow_update_status.cpickle
22:21:28 workflow.py:2444 DEBUG    update_data : {u'available': False}
22:21:28 workflow.py:2225 DEBUG    Workflow version : 1.0.3
22:21:28 workflow.py:1628 DEBUG    Reading settings from `/Users/ekropotin/Library/Application Support/Alfred 3/Workflow Data/com.k15t.labs.alfredapp.confluence.quicksearch/settings.json` ...
22:21:28 workflow.py:2514 DEBUG    Update check not due
22:21:28 workflow.py:2633 DEBUG    Got password : com.k15t.labs.alfredapp.confluence.quicksearch:confluence_password
22:21:28 alfred-confluence.py:59 INFO     ~~ Checking config..
22:21:28 alfred-confluence.py:60 INFO     ~~   baseUrl: https://<myorg>.atlassian.net/wiki
22:21:28 alfred-confluence.py:61 INFO     ~~   username: <myemail>
22:21:28 alfred-confluence.py:62 INFO     ~~   password: <mypassword>
22:21:28 alfred-confluence.py:67 INFO     ~~   Status code: 403
22:21:28 alfred-confluence.py:68 INFO     ~~   ... Failed.
22:21:29 workflow.py:2243 ERROR    HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/ekropotin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3290EE63-D45A-4B8C-8374-AAAA752EF8AB/lib/workflow/workflow.py", line 2236, in run
    func(self)
  File "alfred-confluence.py", line 128, in main
    r.raise_for_status()
  File "/Users/ekropotin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3290EE63-D45A-4B8C-8374-AAAA752EF8AB/lib/workflow/web.py", line 402, in raise_for_status
    raise self.error
HTTPError: HTTP Error 403: Forbidden
22:21:29 workflow.py:2267 DEBUG    Workflow finished in 0.831 seconds.
[2020-01-25 22:21:29][WARNING: input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 64.)'. Row 2, Col 165: 'XML declaration allowed only at the start of the document' in XML:
<?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Authentication failed.</title><subtitle>CAPTCHA issues? Try to logout and login again in your browser.</subtitle></item></items><?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'com.k15t.labs.alfredapp.confluence.quicksearch'</title><subtitle>HTTP Error 403: Forbidden</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
```

**Comment by Akkadius** [comment]
Ditto; ironically I was trying to get this hooked up again as well

**Comment by kabads** [comment]
+1 here for this issue - I just tried to hook it in and it doesn't work. I get the HTTP Eror 403: Forbidden too.

**Comment by skleinei** [comment]
@ekropotin, @Akkadius, @kabads

Have you tried replacing your password with an API token?

You can create one for yourself here:
https://id.atlassian.com/manage-profile/security/api-tokens

Then it should work.

Cheers,
-Stefan

**Comment by ekropotin** [comment]
@skleinei Thanks! This worked out!
Another issue I had is a wrong baseUrl. 
Was:
`https://<myOrg>.atlassian.net`
Has to be:
`https://<myOrg>.atlassian.net/wiki`
